# Site settings
title: "My Blog Title"
email: superjax08@gmail.com
description: "A clever description here"
baseurl: ""
url: "http://jamessjackson.com"
title_description: "Description Here"
title_image: "https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAArqAAAAJDIyNTk0ZWU0LWRiMDAtNGVjZC1hN2M2LWNkMmY3YTQyN2IyOA.jpg"
# google_analytics: ""
github_repository: https://github.com/superjax
# addthis_id:
post_limit: 10

# Social usernames/URLs
twitter_username: jsjacks0n
github_username:  superjax
# instagram_username:
# reddit_username:
linkedin_link: https://www.linkedin.com/in/superjax08/
# xing_link:
# facebook_link:

# Footer
footer_left: "Based on Carte-Noire Theme by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
